language: python
python:
  - "3.6.1"
install:
  - pip install -r requirements.txt
  - createdb hc
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - python manage.py test
  - coverage run --omit="*/tests/*" --source=hc manage.py test
after_success: coveralls
cache: pip
notifications:
  slack: andela:x4a6Z3h0eVwlWzhOvu4Sc1AT
